apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/part-of: eightknot-app
  name: eightknot-postgres
stringData:
  # TODO: use specific vars
  # POSTGRESQL_USER: cache
  # POSTGRESQL_PASSWORD: somepasswordfortesting
  # POSTGRESQL_DATABASE: augur_cache
  # TODO: decide which postgres image to use
  # image: openshift ubi
  POSTGRESQL_ADMIN_PASSWORD: somepasswordfortesting
  # image: enterprisedb
  POSTGRES_PASSWORD: somepasswordfortesting
